### PR TITLE
Filtering directories with no matches

### PR DESCRIPTION
**Pull request by markburns**
Add a failing test case for #3 

I think that the `"""" failed` flagging functionality was not working, I believe this has the fix, but my bash fu is not that great.
Would be worth giving that part a glance over.

### CODE REVIEW

**Comment by markburns** [comment]
So I believe that this actually now is working correctly.
Prior to adding the double square brackets, the conditional was giving an error if the value of  `$expect` was empty. This worked because it is an error and the condition seems to be evaluated to false. With `[[ $expect = "skip" ]]` it works correctly with or without a value. I.e. no errors printed during the test run.

**Comment by albfan** [comment]
Good job. See [[]] is a bashism http://mywiki.wooledge.org/Bashism

Compare this custom test suite with suite other more up-to-date like nerdtree-git-filter-plugin to take hints of how to implement it

I hope to review and merge next week

**Comment by albfan** [comment]
I have reworked all this stuff into https://github.com/albfan/nerdtree-file-filter-plugin/tree/wip/filter-dir-without-matches.

I will push details inline.

In general, try to focus con implementation and don't add noise with typos, whitespace, or debugging traces

See I don't even see how test case explains new functionality.

Let's start with it

**Comment by markburns** [comment]
Thanks for looking at this. Sorry, I'd forgotten that I'd done the PR from my master, so was not really intending for you to review the WIP attempt at fixing the failing test. 
This PR intention was just to add the (flagged) failing test.

I was going to see if I could get it working, tidy it up, then let you know and do a new PR.
Anyway, thanks for looking at it.

I'll close this one, as I'm nearly there with the implementation.

**Comment by albfan** [comment]
Great.

**Pull request closed without merging**
